spring.application.name=signatrust-poc
server.port=8080

# Logging Configurations
logging.level.org.springframework.web=INFO
logging.level.com.signatrust.poc=DEBUG

# File upload properties (allow larger PDFs)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Keystore properties
signatrust.keystore.path=mock-hsm.p12
signatrust.keystore.password=changeit
signatrust.keystore.alias=poc-signer
